name: Build & Push Docker image to registry

on:
  push:
    branches: [ main ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "sagurov/discord-notification-bot"
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN  }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Show environment variables
      run: |
        echo "DOCKER_IMAGE_NAME: ${DOCKER_IMAGE_NAME}"
        echo "VERSION: ${VERSION}"
    - name: Docker login
      run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${DOCKER_IMAGE_NAME}:latest"
    - name: Push the Docker image
      run: docker push "${DOCKER_IMAGE_NAME}:latest"
